# Generated by Django 3.2.15 on 2022-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20211025_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandasSOResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=255)),
                ('ref_image', models.ImageField(upload_to='pandas/')),
                ('wb_sample', models.FileField(null=True, upload_to='pandas-wb/')),
            ],
        ),
    ]
